from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any


@dataclass(slots=True)
class RetrievedChunk:
    """
    Standardized domain representation of a retrieved document chunk.
    """

    chunk_id: str
    document_id: str
    content: str
    score: float
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class RetrievalRequest:
    """
    Encapsulates retrieval execution parameters.
    """

    query: str
    top_k: int = 5
    score_threshold: float = 0.0
    document_id: str | None = None


@dataclass(slots=True)
class RetrievalResult:
    """
    Standardized result generated by the retrieval subsystem.
    """

    query: str
    chunks: list[RetrievedChunk]
    strategy_name: str
    created_at: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )

    @property
    def total_results(self) -> int:
        return len(self.chunks)
